# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/student_management_db101?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=lOPyjBR6IWMhy7x65gX84yU0m16Gs48QlcEHB3lslt4oERlD7CnLXn+9cv/AE2wf
jwt.expiration-ms=3600000

# Default Admin
app.admin.default-username=admin
app.admin.default-password=Admin@123

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.eduapp.studentmanagement=DEBUG